In [14]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [10]:
df = pd.read_csv('Data/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [13]:
median_bedrooms = df.bedrooms.median()
df.bedrooms = df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [15]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']], df.price)

LinearRegression()

In [17]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [18]:
reg.intercept_

221323.00186540443

In [19]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [21]:
reg.predict([[2500,4,5]])

array([578876.03748933])